#!/bin/bash

for pkg in $( lpf list ); do
   to_remove="$to_remove lpf-$pkg"
   rpm -q ${pkg} &> /dev/null && to_remove="$to_remove $pkg"
done
sudo rpm -e $( echo $to_remove )
sudo rm -rf /var/lib/lpf/rpms/foo /var/lib/lpf/rpms/bar

# vim: set expandtab ts=4 sw=4:
