#!/bin/bash

exec 2> test-update-lpf.log
set -x

sudo rpm -U --force rpms/bar-1.0*rpm
sudo rpm -U --force rpms/lpf-bar-1.0*rpm
set $(lpf state bar)
[[ $2 == 'OK' ]]  || exit 1

sudo rpm -U rpms/lpf-bar-1.1*rpm
set $(lpf state bar)
[[ $2 != 'approve-wait' ]] && exit 1
exit 0

sudo rpm -U --force rpms/lpf-bar-1.0*rpm
set $(lpf state bar)
[[ $2 == 'OK' ]]  || exit 1

# vim: set expandtab ts=4 sw=4:
