#!/usr/bin/bash
scriptdir="$( dirname $( readlink -fn $0 ))/../scripts"
source $scriptdir/lpf-defs.bash
exec &> test-notify.log
set -x

sudo -u pkg-build $scriptdir/lpf-notify remove foo &>/dev/null || :
sudo -u pkg-build $scriptdir/lpf-notify remove bar &>/dev/null || :
rm -rf /var/run/user/$UID/lpf

sudo -u pkg-build $scriptdir/lpf-notify create 'foo' 'approve-wait'
test -f $LPF_VAR/notify/foo/state || exit 1
[ $(cat $LPF_VAR/notify/foo/state) = 'approve-wait' ] || exit 2

$scriptdir/lpf-notify is-message-pending || exit 3
sleep 1
$scriptdir/lpf-notify mute foo
[ -f /var/run/user/$UID/lpf/hide/foo ] || exit 4

$scriptdir/lpf-notify is-message-pending && exit 5


sudo -u pkg-build $scriptdir/lpf-notify remove foo
[ -d $LPF_VAR/notify/foo ] && exit 7

rm -rf /tmp/ivar.log
$scriptdir/lpf unmute foo
$scriptdir/lpf-notify notify-watch "echo ivar >/tmp/ivar.log" &
watcher_pid=$!
sudo -u pkg-build $scriptdir/lpf-notify remove 'foo'
sudo -u pkg-build $scriptdir/lpf-notify create 'foo' 'approve-wait'
sleep 1
[ -f /tmp/ivar.log ] || { exit 8; }
[ $( cat /tmp/ivar.log ) = 'ivar' ] || { kill $watcher_pid; exit 9; }
kill $watcher_pid
exit 0
