#!/usr/bin/env python3
#
# pylint: disable=invalid-name

''' build_error wrapper script. '''

import os.path
import sys

sys.argv.append(os.path.dirname(os.path.realpath(__file__)))

import build_error

build_error.main()

# vim: set expandtab ts=4 sw=4:
