#!/bin/bash
#
# Install builddeps. Runs as root, be careful.

set -e

scriptdir=${scriptdir:-$( dirname $(readlink -fn $0))}
source  $scriptdir/lpf-sudo-defs.bash


for spec in "$@"; do
    if [[ $spec != /usr/share/lpf/packages/* ]]; then
       echo "$0: skipping bad spec (wrong prefix): $spec >&2"
    elif has_meta $spec; then
       echo "$0: skipping bad spec (metacharacters): $spec >&2"
    else
       good_specs="$good_specs $spec"
    fi
done

[ "$good_specs" ] && /usr/bin/yum-builddep -y $good_specs


# vim: set expandtab ts=4 sw=4:
