#!/bin/bash

for rpm in "$@"; do
    if [[ $rpm == /var/lib/lpf/rpms/* ]]; then
       good_rpms="$good_rpms $rpm"
    else
       echo "$0: skipping bad rpm: $rpm" >&2
    fi
done
good_rpms=${good_rpms# }

[ "$good_rpms" ]  || { echo "Nothing to install" >&2; exit 1; }

to_remove=''
for file in $( echo $good_rpms ); do
    pkg=$( rpm -q --qf '%{name}' -p $file ) || continue
    to_remove="$to_remove $pkg"
done
to_remove=${to_remove## }

if [ "$to_remove" ]; then
    current_vers=$( rpm -q --qf '%{version}-%{release}' $to_remove )
    new_vers=$( rpm -q --qf '%{version}-%{release}' -p ${good_rpms% *} )
    install='install'
    [ "$current_vers" = "$new_vers" ] && install='reinstall'
    yum -y shell << EOF
        remove $to_remove
        $install $good_rpms
        run
EOF
else
    yum -y install $good_rpms
fi
