#!/usr/bin/env python3
#
# pylint: disable=invalid-name

''' lpf-gui wrapper script. '''

import os.path
import sys

sys.argv.append(os.path.dirname(os.path.realpath(__file__)))

import lpf_gui_base

lpf_gui_base.main()

# vim: set expandtab ts=4 sw=4:
