#!/bin/bash
#
# Install builddeps. Runs as root, be careful.

set -e

for spec in "$@"; do
    if [[ $spec == /usr/share/lpf/packages/* ]]; then
       good_specs="$good_specs $spec"
    else
       echo "$0: skipping bad spec: $spec >&2"
    fi
done

[ "$good_specs" ] && /usr/bin/yum-builddep $good_specs


# vim: set expandtab ts=4 sw=4:
