#!/bin/bash
#
# Use sudo to kill all children of "my" process group.

pgroup=$(ps -ho pgid $$)
members=$( ps  --sid $pgroup -ho pid)
children=${members/$$/}
if [ -n "${children/ /}" ]; then
    kill -TERM ${children/ /} || :
fi
exit 0
