#!/bin/bash
#
# Use sudo to kill all children.

scriptdir=$( dirname $(readlink -fn $0))

SUDO="sudo${DISPLAY:+ -A}"
export SUDO_ASKPASS=$scriptdir/sudo_askpass

children=$( pgrep -U pkg-build )
if [ "${children/ /}" ]; then
    $SUDO -u pkg-build kill -TERM $children  &> /dev/null || :
fi

children=$( pgrep -f "$scriptdir" -U $USER )
children=${children/$$/}
if [ "${children/ /}" ]; then
    kill -TERM $children  &> /dev/null || :
fi

children=$( pgrep -f /var/lib/lpf/rpms -u root )
if [ "${children/ /}" ]; then
    $SUDO kill -TERM $children  &> /dev/null || :
fi

exit 0


# vim: set expandtab ts=4 sw=4:
