#!/bin/bash
#
# Install rpms, runs as root - be careful.
#

set -e

umask 002

scriptdir=${scriptdir:-$( dirname $(readlink -fn $0))}
source  $scriptdir/lpf-sudo-defs.bash

good_rpms=()
for rpm in "$@"; do
    if [[ $rpm != /var/lib/lpf/rpms/* ]]; then
       echo "$0: skipping bad rpm (wrong prefix): $rpm" >&2
    elif has_meta $rpm; then
       echo "$0: skipping bad rpm (metacharacters): $rpm" >&2
    else
       good_rpms=( ${good_rpms[@]} $rpm )
    fi
done

(( ${#good_rpms} == 0 )) && { echo "$0: Nothing to install" >&2; exit 1; }

dnf -y --allowerasing install ${good_rpms[@]}


# vim: set expandtab ts=4 sw=4:
