#!/usr/bin/env python
#
# pylint: disable=invalid-name

''' notify wrapper script. '''

import os.path
import sys

sys.argv.append(os.path.dirname(os.path.realpath(__file__)))

import notify

notify.main()

# vim: set expandtab ts=4 sw=4:
